
public enum EffectType {
    EFFECT_STAT_INCREASE_SHIELD,
    EFFECT_STAT_INCREASE_RES,
    EFFECT_STAT_INCREASE_CRIT_RATE,
    EFFECT_HEAL,
    EFFECT_TAUNT,
    EFFECT_REFLECT,
    EFFECT_REVIVE,
    EFFECT_CLEANSE,
}
